package tui

import (
	"context"
	"errors"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/vinaycharlie01/grok-build/go/internal/application/chatservice"
	"github.com/vinaycharlie01/grok-build/go/internal/domain/chat"
	"github.com/vinaycharlie01/grok-build/go/internal/domain/ports"
	"github.com/vinaycharlie01/grok-build/go/internal/domain/ports/portsfakes"
)

// newTestModel wires a Model to a portsfakes.FakeLLMProvider (generated by
// counterfeiter from the ports.LLMProvider interface — see
// ports/llm.go's //go:generate directive) stubbed to replay a fixed event
// list, ignoring the session/tools passed to it. Replaces this package's
// former hand-rolled scriptedLLM fake with the generated one.
//
// Uses a cancellable context, cancelled via t.Cleanup, rather than
// context.Background(): most tests here call handleStreamEvent/Update
// directly instead of running the real Bubble Tea loop to completion, so
// the chatservice.Send goroutine a submit() call starts is often left
// with events still unread on its channel once the test returns. That
// goroutine's own emit/sendEvent already selects on ctx.Done() (see
// chatservice's goroutine-leak-safe streaming pattern) specifically to
// unblock in exactly this situation — but only if the context passed to
// New actually gets cancelled. Discovered via go.uber.org/goleak's
// TestMain check (main_test.go) flagging leaked goroutines from
// TestSubmitAppendsUserMessageAndSetsWaiting and
// TestSequentialUpdatesAcrossValueCopiesDoNotPanic, both of which start a
// real Send() and don't fully drain it.
func newTestModel(t *testing.T, events ...ports.StreamEvent) Model {
	t.Helper()

	ch := make(chan ports.StreamEvent, len(events))
	for _, e := range events {
		ch <- e
	}
	close(ch)

	llm := &portsfakes.FakeLLMProvider{}
	llm.StreamChatReturns(ch, nil)

	svc := chatservice.New(llm, nil)
	session := chat.NewSession("s1", "grok-4", "")

	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)
	return New(ctx, svc, session)
}

func TestInitReturnsBlinkCmd(t *testing.T) {
	if newTestModel(t).Init() == nil {
		t.Fatal("Init() = nil, want a non-nil blink cmd")
	}
}

func TestViewBeforeReady(t *testing.T) {
	if got := newTestModel(t).View(); got != "initializing…" {
		t.Fatalf("View() = %q, want the pre-ready placeholder", got)
	}
}

func TestWindowSizeMsgMarksReady(t *testing.T) {
	m := newTestModel(t)

	updated, _ := m.Update(tea.WindowSizeMsg{Width: 80, Height: 24})
	mm := updated.(Model)

	if !mm.ready {
		t.Fatal("want ready=true after a WindowSizeMsg")
	}
	wantWidth := 80 - viewportStyle.GetHorizontalFrameSize()
	if mm.viewport.Width != wantWidth {
		t.Fatalf("viewport.Width = %d, want %d (80 minus the viewport style's border+padding frame)", mm.viewport.Width, wantWidth)
	}
	if got := mm.View(); got == "initializing…" {
		t.Fatal("View() still shows the pre-ready placeholder after WindowSizeMsg")
	}
}

func TestCtrlCAndEscQuit(t *testing.T) {
	for _, key := range []tea.KeyType{tea.KeyCtrlC, tea.KeyEsc} {
		m := newTestModel(t)
		_, cmd := m.Update(tea.KeyMsg{Type: key})
		if cmd == nil {
			t.Fatalf("key %v: want a non-nil quit cmd", key)
		}
		if _, ok := cmd().(tea.QuitMsg); !ok {
			t.Fatalf("key %v: want tea.QuitMsg, got %T", key, cmd())
		}
	}
}

func TestSubmitAppendsUserMessageAndSetsWaiting(t *testing.T) {
	m := newTestModel(t, ports.StreamEvent{Type: ports.EventDone})
	m.input.SetValue("hello there")

	updated, cmd := m.submit()
	mm := updated.(Model)

	if !mm.waiting {
		t.Fatal("want waiting=true immediately after submit")
	}
	if mm.input.Value() != "" {
		t.Fatalf("input.Value() = %q, want it reset", mm.input.Value())
	}
	if !strings.Contains(mm.transcript.String(), "hello there") {
		t.Fatalf("transcript = %q, want it to contain the submitted text", mm.transcript.String())
	}
	if cmd == nil {
		t.Fatal("want a non-nil cmd to kick off streaming")
	}
}

func TestEnterIsIgnoredWhileWaitingOrEmpty(t *testing.T) {
	m := newTestModel(t)
	m.waiting = true
	m.input.SetValue("should not send")

	_, cmd := m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	if cmd != nil {
		t.Fatal("want nil cmd when a turn is already in flight")
	}

	m.waiting = false
	m.input.SetValue("")
	_, cmd = m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	if cmd != nil {
		t.Fatal("want nil cmd for an empty prompt")
	}
}

func TestHandleStreamEventTextDelta(t *testing.T) {
	m := newTestModel(t)
	updated, cmd := m.handleStreamEvent(ports.StreamEvent{Type: ports.EventTextDelta, Text: "hello"})
	mm := updated.(Model)

	if !strings.Contains(mm.transcript.String(), "hello") {
		t.Fatalf("transcript = %q, want it to contain the streamed text", mm.transcript.String())
	}
	if mm.streaming.String() != "hello" {
		t.Fatalf("streaming buffer = %q, want %q", mm.streaming.String(), "hello")
	}
	if cmd == nil {
		t.Fatal("want a non-nil cmd to keep draining the event channel")
	}
}

func TestHandleStreamEventToolCall(t *testing.T) {
	m := newTestModel(t)
	tc := chat.ToolCall{ID: "1", Name: "shell_exec", Arguments: `{"command":"ls"}`}

	updated, _ := m.handleStreamEvent(ports.StreamEvent{Type: ports.EventToolCall, ToolCall: tc})
	mm := updated.(Model)

	if !strings.Contains(mm.transcript.String(), "shell_exec") {
		t.Fatalf("transcript = %q, want it to mention the tool call", mm.transcript.String())
	}
}

func TestHandleStreamEventDoneResetsStreamingBuffer(t *testing.T) {
	m := newTestModel(t)
	m.streaming.WriteString("partial")

	updated, _ := m.handleStreamEvent(ports.StreamEvent{Type: ports.EventDone})
	mm := updated.(Model)

	if mm.streaming.Len() != 0 {
		t.Fatalf("streaming buffer = %q, want it reset on EventDone", mm.streaming.String())
	}
}

func TestHandleStreamEventErrorRecordsAndRenders(t *testing.T) {
	m := newTestModel(t)
	wantErr := errors.New("boom")

	updated, _ := m.handleStreamEvent(ports.StreamEvent{Type: ports.EventError, Err: wantErr})
	mm := updated.(Model)

	if !errors.Is(mm.err, wantErr) {
		t.Fatalf("err = %v, want %v", mm.err, wantErr)
	}
	if !strings.Contains(mm.transcript.String(), "boom") {
		t.Fatalf("transcript = %q, want it to mention the error", mm.transcript.String())
	}
}

func TestStreamClosedMsgClearsWaiting(t *testing.T) {
	m := newTestModel(t)
	m.waiting = true

	updated, cmd := m.Update(streamClosedMsg{})
	mm := updated.(Model)

	if mm.waiting {
		t.Fatal("want waiting=false after streamClosedMsg")
	}
	if cmd != nil {
		t.Fatal("want a nil cmd on stream close")
	}
}

func TestWaitForEventTranslatesChannel(t *testing.T) {
	ch := make(chan ports.StreamEvent, 1)
	ch <- ports.StreamEvent{Type: ports.EventDone}

	msg := waitForEvent(ch)()
	ev, ok := msg.(streamEventMsg)
	if !ok {
		t.Fatalf("want streamEventMsg, got %T", msg)
	}
	if ev.event.Type != ports.EventDone {
		t.Fatalf("event.Type = %v, want EventDone", ev.event.Type)
	}

	close(ch)
	if _, ok := waitForEvent(ch)().(streamClosedMsg); !ok {
		t.Fatal("want streamClosedMsg once the channel is closed")
	}
}

// TestSequentialUpdatesAcrossValueCopiesDoNotPanic simulates the real
// Bubble Tea event loop: Update takes and returns tea.Model by value on
// every single call, so the framework copies our Model constantly. Every
// prior test in this file called submit/handleStreamEvent/Update exactly
// once on a freshly-constructed model, which never exercises writing to
// the same logical model's transcript/streaming buffers across more than
// one value-copy — exactly the scenario that panics with "strings:
// illegal use of non-zero Builder copied by value" if those fields are
// plain strings.Builder values instead of pointers. This test reassigns
// through the tea.Model interface on every step, the same way
// bubbletea.Program.Run's real event loop does, specifically to catch
// that class of bug.
func TestSequentialUpdatesAcrossValueCopiesDoNotPanic(t *testing.T) {
	var tm tea.Model = newTestModel(t)

	step := func(msg tea.Msg) {
		t.Helper()
		var cmd tea.Cmd
		tm, cmd = tm.Update(msg)
		if cmd != nil {
			if resultMsg := cmd(); resultMsg != nil {
				tm, _ = tm.Update(resultMsg)
			}
		}
	}

	step(tea.WindowSizeMsg{Width: 80, Height: 24})

	mm := tm.(Model)
	mm.input.SetValue("first message")
	tm = mm

	step(tea.KeyMsg{Type: tea.KeyEnter}) // submit() writes to transcript for the 2nd time overall
	step(streamEventMsg{event: ports.StreamEvent{Type: ports.EventTextDelta, Text: "chunk one "}})
	step(streamEventMsg{event: ports.StreamEvent{Type: ports.EventTextDelta, Text: "chunk two"}})
	step(streamEventMsg{event: ports.StreamEvent{Type: ports.EventDone}})
	step(streamClosedMsg{})

	mm = tm.(Model)
	mm.input.SetValue("second message")
	tm = mm
	step(tea.KeyMsg{Type: tea.KeyEnter}) // a 2nd full turn - more copies, more writes

	final := tm.(Model)
	got := final.transcript.String()
	for _, want := range []string{"first message", "chunk one", "chunk two", "second message"} {
		if !strings.Contains(got, want) {
			t.Fatalf("transcript = %q, want it to contain %q", got, want)
		}
	}
}
