// Code generated by counterfeiter. DO NOT EDIT.
package portsfakes

import (
	"context"
	"sync"

	"github.com/vinaycharlie01/grok-build/go/internal/domain/chat"
	"github.com/vinaycharlie01/grok-build/go/internal/domain/ports"
)

type FakeLLMProvider struct {
	StreamChatStub        func(context.Context, *chat.Session, []ports.ToolSpec) (<-chan ports.StreamEvent, error)
	streamChatMutex       sync.RWMutex
	streamChatArgsForCall []struct {
		arg1 context.Context
		arg2 *chat.Session
		arg3 []ports.ToolSpec
	}
	streamChatReturns struct {
		result1 <-chan ports.StreamEvent
		result2 error
	}
	streamChatReturnsOnCall map[int]struct {
		result1 <-chan ports.StreamEvent
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLLMProvider) StreamChat(arg1 context.Context, arg2 *chat.Session, arg3 []ports.ToolSpec) (<-chan ports.StreamEvent, error) {
	var arg3Copy []ports.ToolSpec
	if arg3 != nil {
		arg3Copy = make([]ports.ToolSpec, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.streamChatMutex.Lock()
	ret, specificReturn := fake.streamChatReturnsOnCall[len(fake.streamChatArgsForCall)]
	fake.streamChatArgsForCall = append(fake.streamChatArgsForCall, struct {
		arg1 context.Context
		arg2 *chat.Session
		arg3 []ports.ToolSpec
	}{arg1, arg2, arg3Copy})
	stub := fake.StreamChatStub
	fakeReturns := fake.streamChatReturns
	fake.recordInvocation("StreamChat", []interface{}{arg1, arg2, arg3Copy})
	fake.streamChatMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLLMProvider) StreamChatCallCount() int {
	fake.streamChatMutex.RLock()
	defer fake.streamChatMutex.RUnlock()
	return len(fake.streamChatArgsForCall)
}

func (fake *FakeLLMProvider) StreamChatCalls(stub func(context.Context, *chat.Session, []ports.ToolSpec) (<-chan ports.StreamEvent, error)) {
	fake.streamChatMutex.Lock()
	defer fake.streamChatMutex.Unlock()
	fake.StreamChatStub = stub
}

func (fake *FakeLLMProvider) StreamChatArgsForCall(i int) (context.Context, *chat.Session, []ports.ToolSpec) {
	fake.streamChatMutex.RLock()
	defer fake.streamChatMutex.RUnlock()
	argsForCall := fake.streamChatArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeLLMProvider) StreamChatReturns(result1 <-chan ports.StreamEvent, result2 error) {
	fake.streamChatMutex.Lock()
	defer fake.streamChatMutex.Unlock()
	fake.StreamChatStub = nil
	fake.streamChatReturns = struct {
		result1 <-chan ports.StreamEvent
		result2 error
	}{result1, result2}
}

func (fake *FakeLLMProvider) StreamChatReturnsOnCall(i int, result1 <-chan ports.StreamEvent, result2 error) {
	fake.streamChatMutex.Lock()
	defer fake.streamChatMutex.Unlock()
	fake.StreamChatStub = nil
	if fake.streamChatReturnsOnCall == nil {
		fake.streamChatReturnsOnCall = make(map[int]struct {
			result1 <-chan ports.StreamEvent
			result2 error
		})
	}
	fake.streamChatReturnsOnCall[i] = struct {
		result1 <-chan ports.StreamEvent
		result2 error
	}{result1, result2}
}

func (fake *FakeLLMProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLLMProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ports.LLMProvider = new(FakeLLMProvider)
