// Code generated by counterfeiter. DO NOT EDIT.
package portsfakes

import (
	"sync"

	"github.com/vinaycharlie01/grok-build/go/internal/domain/ports"
)

type FakeCredentialStore struct {
	APIKeyStub        func() (string, error)
	aPIKeyMutex       sync.RWMutex
	aPIKeyArgsForCall []struct {
	}
	aPIKeyReturns struct {
		result1 string
		result2 error
	}
	aPIKeyReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredentialStore) APIKey() (string, error) {
	fake.aPIKeyMutex.Lock()
	ret, specificReturn := fake.aPIKeyReturnsOnCall[len(fake.aPIKeyArgsForCall)]
	fake.aPIKeyArgsForCall = append(fake.aPIKeyArgsForCall, struct {
	}{})
	stub := fake.APIKeyStub
	fakeReturns := fake.aPIKeyReturns
	fake.recordInvocation("APIKey", []interface{}{})
	fake.aPIKeyMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredentialStore) APIKeyCallCount() int {
	fake.aPIKeyMutex.RLock()
	defer fake.aPIKeyMutex.RUnlock()
	return len(fake.aPIKeyArgsForCall)
}

func (fake *FakeCredentialStore) APIKeyCalls(stub func() (string, error)) {
	fake.aPIKeyMutex.Lock()
	defer fake.aPIKeyMutex.Unlock()
	fake.APIKeyStub = stub
}

func (fake *FakeCredentialStore) APIKeyReturns(result1 string, result2 error) {
	fake.aPIKeyMutex.Lock()
	defer fake.aPIKeyMutex.Unlock()
	fake.APIKeyStub = nil
	fake.aPIKeyReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCredentialStore) APIKeyReturnsOnCall(i int, result1 string, result2 error) {
	fake.aPIKeyMutex.Lock()
	defer fake.aPIKeyMutex.Unlock()
	fake.APIKeyStub = nil
	if fake.aPIKeyReturnsOnCall == nil {
		fake.aPIKeyReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.aPIKeyReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCredentialStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredentialStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ports.CredentialStore = new(FakeCredentialStore)
