package main

import (
	"context"
	"errors"
	"testing"

	"github.com/vinaycharlie01/grok-build/go/internal/domain/chat"
	"github.com/vinaycharlie01/grok-build/go/internal/domain/ports"
	"github.com/vinaycharlie01/grok-build/go/internal/domain/ports/portsfakes"
)

// These tests use portsfakes.FakeSessionStore — generated by counterfeiter
// from the ports.SessionStore interface (see ports/session_store.go's
// //go:generate directive) — rather than a hand-rolled fake. See README.md's
// "Mocking port interfaces" for when a generated fake is preferred over a
// hand-rolled one (this package's resolveSession only needs fixed
// Load return values per test, no call-indexed scripting, so the
// generated fake's .LoadReturns/.LoadCallCount/.LoadArgsForCall cover it
// with less code than a hand-rolled in-memory map would).

func TestResolveSessionWithNilStoreCreatesFresh(t *testing.T) {
	got, err := resolveSession(context.Background(), nil, "local", "grok-4", "be terse")
	if err != nil {
		t.Fatalf("resolveSession() error = %v", err)
	}
	if got.ID != "local" || got.Model != "grok-4" {
		t.Fatalf("resolveSession() = %+v, want a fresh session for id/model", got)
	}
	if len(got.Messages) != 1 || got.Messages[0].Content != "be terse" {
		t.Fatalf("resolveSession() = %+v, want it seeded with the system prompt", got)
	}
}

func TestResolveSessionLoadsPersistedSessionWhenPresent(t *testing.T) {
	saved := chat.NewSession("local", "grok-4", "")
	saved.Append(chat.UserMessage("earlier turn"))

	store := &portsfakes.FakeSessionStore{}
	store.LoadReturns(saved, nil)

	got, err := resolveSession(context.Background(), store, "local", "grok-4", "be terse")
	if err != nil {
		t.Fatalf("resolveSession() error = %v", err)
	}
	if got != saved {
		t.Fatalf("resolveSession() = %+v, want the persisted session %+v returned as-is (not re-seeded)", got, saved)
	}
	if store.LoadCallCount() != 1 {
		t.Fatalf("store.Load() called %d times, want 1", store.LoadCallCount())
	}
	if _, gotID := store.LoadArgsForCall(0); gotID != "local" {
		t.Fatalf("store.Load() called with id %q, want %q", gotID, "local")
	}
}

func TestResolveSessionFallsBackToFreshWhenStoreHasNothingSaved(t *testing.T) {
	store := &portsfakes.FakeSessionStore{}
	store.LoadReturns(nil, ports.ErrSessionNotFound)

	got, err := resolveSession(context.Background(), store, "local", "grok-4", "be terse")
	if err != nil {
		t.Fatalf("resolveSession() error = %v", err)
	}
	if got.ID != "local" || len(got.Messages) != 1 {
		t.Fatalf("resolveSession() = %+v, want a fresh seeded session when nothing was persisted yet", got)
	}
}

func TestResolveSessionPropagatesUnexpectedStoreErrors(t *testing.T) {
	store := &portsfakes.FakeSessionStore{}
	store.LoadReturns(nil, errors.New("connection refused"))

	if _, err := resolveSession(context.Background(), store, "local", "grok-4", ""); err == nil {
		t.Fatal("resolveSession() error = nil, want the store's non-not-found error to propagate")
	}
}
